### ISSUE TITLE
cmake version on lxplus changed... need to update example

### ISSUE THREAD

**Issue by terzo** [eutelescope/iLCInstall#20]
In iLCInstall/examples/eutelescope/release-atlascvmfs-lxplus.cfg
cmake version should be changed from 3.10.0 to 3.11.0 since the present version is no more available on lxplus.

**Comment by edorossi** [comment]
Ciao Stefano,

I am very sorry, I had not see your issue here. I was not "watching" this folder, I fixed it now. I just changed the version to 3.11.0!

Cheers,

Edo
